#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "workspace/shark-foundation/data"
OUTPUT = ROOT / "workspace/ui/src/generated/uib-actions.ts"

SELECTORS = {
    "documentSelectRegister": "DOCUMENT.SELECT_REGISTER",
    "documentVerify": "DOCUMENT.VERIFY",
    "documentList": "DOCUMENT.LIST",
    "documentOpenView": "DOCUMENT.OPEN_VIEW",
    "documentAttach": "DOCUMENT.ATTACH",
    "ocrExtract": "OCR.EXTRACT_RECEIPT",
    "receiptSuggestBank": "RECEIPT.SUGGEST_BANK",
    "receiptConfirmBank": "RECEIPT.CONFIRM_BANK",
    "receiptRejectBank": "RECEIPT.REJECT_BANK",
    "contactsList": "CONTACTS.LIST",
    "contactsSave": "CONTACTS.SAVE",
    "reportSummary": "REPORT.SUMMARY",
    "settingsBooksInfo": "SETTINGS.BOOKS_INFO",
    "settingsStorageRoot": "SETTINGS.STORAGE_ROOT.SELECT",
}

def load_actions():
    rows = []
    for index in range(1, 25):
        path = REGISTRY / f"action_registry_v1_chunk{index:02d}.jsonl"
        if not path.is_file():
            raise SystemExit(f"missing registry chunk: {path}")
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                rows.append(json.loads(line))
    if len(rows) != 206:
        raise SystemExit(f"expected 206 canonical actions, found {len(rows)}")
    ids = [row["action_id"] for row in rows]
    if len(set(ids)) != 206:
        raise SystemExit("Action Registry IDs are not unique")
    return rows

def resolve(rows):
    selected = {}
    for key, action_id in SELECTORS.items():
        matches = [row for row in rows if row["action_id"] == action_id]
        if len(matches) != 1:
            raise SystemExit(f"{key}/{action_id} matched {len(matches)} ActionSpecs")
        selected[key] = matches[0]
    action_ids = [row["action_id"] for row in selected.values()]
    if len(selected) != 14 or len(set(action_ids)) != 14:
        raise SystemExit("UI-B selectors are not exactly 14 one-to-one canonical ActionSpecs")
    return selected

def shape(row):
    return {
        "actionId": row["action_id"],
        "manualLabel": row["manual_label"],
        "family": row["family"],
        "authorityClass": row["authority_class"],
        "confirmationClass": row["confirmation_class"],
        "confirmationPolicy": row["confirmation_policy"],
        "requiredSlots": row["required_slots"],
        "choiceHints": row["choice_hints"],
        "availabilityState": row["availability_state"],
        "backendState": row["backend_state"],
    }

def render(selected):
    payload = json.dumps({key: shape(row) for key, row in selected.items()}, ensure_ascii=False, indent=2)
    return (
        "// GENERATED by scripts/generate_sbc7b2_uib_actions.py. DO NOT EDIT.\n"
        "// Semantic fields come directly from the canonical Shark Action Registry.\n\n"
        f"export const UIB_ACTIONS = {payload} as const;\n\n"
        "export type UiBActionKey = keyof typeof UIB_ACTIONS;\n"
    )

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--audit", action="store_true")
    args = parser.parse_args()
    rows = load_actions()
    selected = resolve(rows)
    if args.audit:
        print("PASS: 14 UI-B Action selectors resolve one-to-one")
        for key in SELECTORS:
            print(f"{key} -> {selected[key]['action_id']}")
        return
    rendered = render(selected)
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit("generated UI-B Action metadata is missing or stale")
        print("PASS: generated UI-B Action metadata is reproducible")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"WROTE {OUTPUT.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
