use std::{fs, path::Path};

const AUTOGENERATED_PERMISSIONS_DIR: &str = "permissions/autogenerated";

fn main() {
    let autogenerated = Path::new(AUTOGENERATED_PERMISSIONS_DIR);
    if autogenerated.exists() {
        fs::remove_dir_all(autogenerated)
            .expect("failed to clear stale Tauri autogenerated application permissions");
    }

    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "foundation_health",
                "production_encryption_required",
                "books_create",
                "books_open",
                "books_verify",
                "books_trial_balance",
            ]),
        ),
    )
    .expect("failed to build Shark Books Community Tauri manifest");
}
