use std::{fs, path::Path};

const AUTOGENERATED_PERMISSIONS_DIR: &str = "permissions/autogenerated";

fn main() {
    let autogenerated = Path::new(AUTOGENERATED_PERMISSIONS_DIR);
    if autogenerated.exists() {
        fs::remove_dir_all(autogenerated)
            .expect("failed to clear stale Tauri autogenerated application permissions");
    }

    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "foundation_health",
                "production_encryption_required",
                "books_create",
                "books_open",
                "books_verify",
                "books_trial_balance",
                "ocr_extract_receipt",
                "owner_home_status",
                "owner_money_in_preview",
                "owner_money_in_save",
                "owner_money_out_preview",
                "owner_money_out_save",
                "owner_bank_import_preview_csv",
                "owner_bank_import_preview_ofx_qfx",
                "owner_bank_match_review",
                "owner_bank_reconcile_preview",
                "owner_bank_import_confirm_csv",
                "owner_bank_import_confirm_ofx_qfx",
                "owner_bank_activity_list",
                "owner_bank_match_confirm",
                "owner_bank_reconcile_finalise",
                "owner_document_select_register",
                "owner_document_verify",
                "owner_document_attach",
                "owner_ocr_extract_receipt",
            ]),
        ),
    )
    .expect("failed to build Shark Books Community Tauri manifest");
}
