#!/bin/bash
set -u
set -o pipefail

BASE_HEAD="b1ba585c9c739432e3328a7ed1475ae690fb5b9c"
BEANKEEPER_PIN="d573db5e61089b0922f95c991732394d08e3cf92"
FACADE_SHA="6274cffc89ccb2fcea4d489e76375c9c5be1e3c8cc2fbd4c4e56b37bdef0ef46"
LOCK_SHA_EXPECTED="3239385c688f64120a6701cdf3f603134950902f2591bae6b7be7248388ec4a9"
TAURI_CLI_VERSION="2.11.4"
TAURI_CORE_VERSION="2.11.5"
TAURI_BUILD_VERSION="2.6.3"
RUST_TOOLCHAIN="${RUST_TOOLCHAIN:-1.98.1}"

REPO_ROOT="${CM_BUILD_DIR:-$(cd "$(dirname "$0")/.." && pwd)}"
WORKSPACE="$REPO_ROOT/workspace"
TAURI_APP="$WORKSPACE/shark-tauri-spike"
ARTIFACTS="$REPO_ROOT/artifacts"
TOOLS="$ARTIFACTS/tools/tauri-cli"
TS="$(date +%Y%m%d_%H%M%S)"
RESULT_DIR="$ARTIFACTS/sbc1e_$TS"
LOG_DIR="$RESULT_DIR/logs"
RESULT_ZIP="$ARTIFACTS/SBC1E_CODEMAGIC_RESULT_$TS.zip"
SUMMARY_TXT="$ARTIFACTS/SBC1E_SUMMARY.txt"
SUMMARY_JSON="$ARTIFACTS/SBC1E_SUMMARY.json"
mkdir -p "$LOG_DIR" "$TOOLS"

CMD_N=0
ASSERT_N=0
FAIL_N=0
PHASE="PREP"
OVERALL="FAIL"
CLASSIFICATION="UNRESOLVED"
LOCK_SHA=""
XCODE_VERSION=""
RUSTC_VERSION=""
CARGO_VERSION=""
TAURI_VERSION=""
APP_PATH=""

json_escape() {
  python3 -c 'import json,sys; print(json.dumps(sys.stdin.read())[1:-1])'
}

pass() {
  ASSERT_N=$((ASSERT_N+1))
  printf 'PASS\t%s\n' "$1" >> "$RESULT_DIR/assertions.tsv"
  printf '[PASS] %s\n' "$1"
}

fail() {
  ASSERT_N=$((ASSERT_N+1))
  FAIL_N=$((FAIL_N+1))
  printf 'FAIL\t%s\n' "$1" >> "$RESULT_DIR/assertions.tsv"
  printf '[FAIL] %s\n' "$1"
}

run_cmd() {
  label="$1"
  shift
  CMD_N=$((CMD_N+1))
  num="$(printf '%03d' "$CMD_N")"
  printf '%q ' "$@" > "$LOG_DIR/${num}_${label}.command.txt"
  printf '\n' >> "$LOG_DIR/${num}_${label}.command.txt"
  "$@" >"$LOG_DIR/${num}_${label}.stdout.txt" 2>"$LOG_DIR/${num}_${label}.stderr.txt"
  rc=$?
  printf 'exit_code=%s\n' "$rc" > "$LOG_DIR/${num}_${label}.result.txt"
  return "$rc"
}

stop() {
  fail "$1"
  CLASSIFICATION="$2"
  exit "${3:-1}"
}

finish() {
  rc=$?
  set +e
  [ -f "$WORKSPACE/Cargo.lock" ] && shasum -a 256 "$WORKSPACE/Cargo.lock" > "$RESULT_DIR/Cargo.lock.sha256"
  git -C "$REPO_ROOT" status --short > "$RESULT_DIR/git_status_at_finish.txt" 2>/dev/null || true
  git -C "$REPO_ROOT" rev-parse HEAD > "$RESULT_DIR/repository_commit.txt" 2>/dev/null || true
  find "$TAURI_APP/gen/apple" -maxdepth 8 -type f \( -name 'project.pbxproj' -o -name 'Info.plist' -o -name 'Podfile' -o -name '*.xcconfig' \) -print > "$RESULT_DIR/apple_project_files.txt" 2>/dev/null || true
  find "$TAURI_APP/permissions/autogenerated" -maxdepth 1 -type f -name '*.toml' -print > "$RESULT_DIR/autogenerated_permission_files.txt" 2>/dev/null || true
  df -h > "$RESULT_DIR/disk_at_finish.txt" 2>/dev/null || true

  cat > "$SUMMARY_TXT" <<EOF
SBC-1E Codemagic iOS Shell Proof
Overall: $OVERALL
Classification: $CLASSIFICATION
Phase: $PHASE
Assertions: $ASSERT_N
Failures: $FAIL_N
Commands: $CMD_N
Codemagic build id: ${CM_BUILD_ID:-unknown}
Codemagic workflow id: ${CM_WORKFLOW_ID:-unknown}
Repository commit: ${CM_COMMIT:-unknown}
Base SBC-1D head: $BASE_HEAD
Beankeeper pin: $BEANKEEPER_PIN
Approved SBC-1C facade SHA-256: $FACADE_SHA
Reviewed Cargo.lock SHA-256: $LOCK_SHA_EXPECTED
Observed Cargo.lock SHA-256: $LOCK_SHA
Rust toolchain: $RUST_TOOLCHAIN
rustc: $RUSTC_VERSION
cargo: $CARGO_VERSION
Tauri CLI: $TAURI_VERSION
Tauri core pin: $TAURI_CORE_VERSION
Tauri build pin: $TAURI_BUILD_VERSION
Xcode: $XCODE_VERSION
Built app path: $APP_PATH
EOF

  cat > "$SUMMARY_JSON" <<EOF
{
  "overall": "$(printf '%s' "$OVERALL" | json_escape)",
  "classification": "$(printf '%s' "$CLASSIFICATION" | json_escape)",
  "phase": "$(printf '%s' "$PHASE" | json_escape)",
  "assertions": $ASSERT_N,
  "failures": $FAIL_N,
  "commands": $CMD_N,
  "codemagic_build_id": "$(printf '%s' "${CM_BUILD_ID:-unknown}" | json_escape)",
  "codemagic_workflow_id": "$(printf '%s' "${CM_WORKFLOW_ID:-unknown}" | json_escape)",
  "repository_commit": "$(printf '%s' "${CM_COMMIT:-unknown}" | json_escape)",
  "base_head": "$BASE_HEAD",
  "beankeeper_pin": "$BEANKEEPER_PIN",
  "sbc1c_facade_sha256": "$FACADE_SHA",
  "reviewed_cargo_lock_sha256": "$LOCK_SHA_EXPECTED",
  "observed_cargo_lock_sha256": "$(printf '%s' "$LOCK_SHA" | json_escape)",
  "rust_toolchain": "$RUST_TOOLCHAIN",
  "rustc_version": "$(printf '%s' "$RUSTC_VERSION" | json_escape)",
  "cargo_version": "$(printf '%s' "$CARGO_VERSION" | json_escape)",
  "tauri_cli_version": "$(printf '%s' "$TAURI_VERSION" | json_escape)",
  "xcode_version": "$(printf '%s' "$XCODE_VERSION" | json_escape)",
  "built_app_path": "$(printf '%s' "$APP_PATH" | json_escape)"
}
EOF

  cp "$SUMMARY_TXT" "$RESULT_DIR/SUMMARY.txt" 2>/dev/null || true
  cp "$SUMMARY_JSON" "$RESULT_DIR/SUMMARY.json" 2>/dev/null || true
  rm -f "$RESULT_ZIP"
  if command -v ditto >/dev/null 2>&1; then
    ditto -c -k --sequesterRsrc --keepParent "$RESULT_DIR" "$RESULT_ZIP" 2>/dev/null || true
  fi
  if [ ! -f "$RESULT_ZIP" ]; then
    (cd "$ARTIFACTS" && zip -qry "$RESULT_ZIP" "$(basename "$RESULT_DIR")") || true
  fi
  [ -f "$RESULT_ZIP" ] && shasum -a 256 "$RESULT_ZIP" > "$RESULT_ZIP.sha256" 2>/dev/null || true
  echo "OVERALL: $OVERALL"
  echo "Classification: $CLASSIFICATION"
  exit "$rc"
}
trap finish EXIT
: > "$RESULT_DIR/assertions.tsv"

# ---------- E0: host and repository preflight ----------
PHASE="E0_PREFLIGHT"
[ "$(uname -s)" = "Darwin" ] || stop "Host is macOS" "HOST_NOT_MACOS" 20
pass "Host is macOS"
[ "$(uname -m)" = "arm64" ] || stop "Host is Apple Silicon arm64" "HOST_NOT_ARM64" 21
pass "Host is Apple Silicon arm64"

for tool in git curl xcodebuild xcrun pod python3 shasum zip; do
  command -v "$tool" >/dev/null 2>&1 || stop "$tool available" "HOST_PREREQUISITE_MISSING_$tool" 22
  pass "$tool available"
done

if run_cmd xcode_version xcodebuild -version; then
  XCODE_VERSION="$(tr '\n' ' ' < "$LOG_DIR/$(printf '%03d' "$CMD_N")_xcode_version.stdout.txt" | sed 's/[[:space:]]*$//')"
  pass "Xcode responds"
else
  stop "Xcode responds" "XCODE_NOT_READY" 23
fi
run_cmd iphoneos_sdk xcrun --sdk iphoneos --show-sdk-path || stop "iphoneos SDK visible" "IPHONEOS_SDK_MISSING" 24
pass "iphoneos SDK visible"
run_cmd iphonesimulator_sdk xcrun --sdk iphonesimulator --show-sdk-path || stop "iphonesimulator SDK visible" "IPHONESIMULATOR_SDK_MISSING" 25
pass "iphonesimulator SDK visible"
run_cmd pod_version pod --version || stop "CocoaPods responds" "COCOAPODS_BROKEN" 25
pass "CocoaPods responds"

if [ -n "$(git -C "$REPO_ROOT" status --porcelain 2>/dev/null)" ]; then
  stop "Repository is clean before SBC-1E build generation" "REPOSITORY_DIRTY_AT_ENTRY" 26
fi
pass "Repository is clean before SBC-1E build generation"

HEAD="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"
[ -n "$HEAD" ] || stop "Repository HEAD resolves" "REPOSITORY_HEAD_MISSING" 26
pass "Repository HEAD resolves"
if [ -n "${CM_COMMIT:-}" ] && [ "$HEAD" != "$CM_COMMIT" ]; then
  stop "Checked-out HEAD matches Codemagic commit" "CODEMAGIC_COMMIT_MISMATCH" 27
fi
pass "Checked-out HEAD matches Codemagic commit"

git -C "$REPO_ROOT" merge-base --is-ancestor "$BASE_HEAD" "$HEAD" >/dev/null 2>&1 || stop "SBC-1D PASS head is ancestor of candidate" "BASE_HEAD_NOT_ANCESTOR" 28
pass "SBC-1D PASS head is ancestor of candidate"

EXPECTED_CHANGED="$(cat <<'EOF'
ci/run_sbc1e_codemagic.sh
codemagic.yaml
docs/SBC1E_IOS_SHELL_CANDIDATE_CONTRACT_2026-09-05.json
workspace/shark-tauri-spike/capabilities/ios-main.json
workspace/shark-tauri-spike/tauri.ios.conf.json
EOF
)"
OBSERVED_CHANGED="$(git -C "$REPO_ROOT" diff --name-only "$BASE_HEAD..$HEAD" | LC_ALL=C sort)"
if [ "$OBSERVED_CHANGED" != "$EXPECTED_CHANGED" ]; then
  printf '%s\n' "$OBSERVED_CHANGED" > "$RESULT_DIR/observed_changed_files.txt"
  stop "Candidate changes are exactly the five authorised SBC-1E files" "UNAUTHORISED_SOURCE_CHANGE" 29
fi
pass "Candidate changes are exactly the five authorised SBC-1E files"

# ---------- E1: immutable baseline + iOS ACL semantics ----------
PHASE="E1_BASELINE_AND_IOS_ACL"
if run_cmd baseline_guard python3 "$REPO_ROOT/scripts/check_frozen_baseline.py"; then
  pass "Frozen foundation and SBC-1D baseline guard passes unchanged"
else
  stop "Frozen foundation and SBC-1D baseline guard passes unchanged" "FROZEN_BASELINE_GUARD_FAIL" 30
fi

if python3 - "$REPO_ROOT" >"$LOG_DIR/ios_acl_check.stdout.txt" 2>"$LOG_DIR/ios_acl_check.stderr.txt" <<'PY'
import json, pathlib, sys
root = pathlib.Path(sys.argv[1])
base = json.loads((root / "workspace/shark-tauri-spike/tauri.conf.json").read_text())
ios_cfg = json.loads((root / "workspace/shark-tauri-spike/tauri.ios.conf.json").read_text())
win_cap = json.loads((root / "workspace/shark-tauri-spike/capabilities/default.json").read_text())
ios_cap = json.loads((root / "workspace/shark-tauri-spike/capabilities/ios-main.json").read_text())
permission = (root / "workspace/shark-tauri-spike/permissions/shark-shell.toml").read_text()

assert base["app"]["security"]["capabilities"] == ["windows-main"]
assert ios_cfg == {"app": {"security": {"capabilities": ["ios-main"]}}}
assert win_cap["identifier"] == "windows-main"
assert win_cap["platforms"] == ["windows"]
assert win_cap["windows"] == ["main"]
assert win_cap["permissions"] == ["shark-shell"]
assert win_cap["local"] is True
assert ios_cap["identifier"] == "ios-main"
assert ios_cap["platforms"] == ["iOS"]
assert ios_cap["windows"] == ["main"]
assert ios_cap["permissions"] == ["shark-shell"]
assert ios_cap["local"] is True
assert "core:default" not in json.dumps(ios_cap)
for command in (
    "foundation_health",
    "production_encryption_required",
    "books_create",
    "books_open",
    "books_verify",
    "books_trial_balance",
):
    assert f'"{command}"' in permission
print("PASS: Windows remains windows-main only; iOS selects ios-main only; both reuse shark-shell.")
PY
then
  pass "iOS capability is separate, iOS-only and bounded to shark-shell"
else
  stop "iOS capability is separate, iOS-only and bounded to shark-shell" "IOS_CAPABILITY_POLICY_FAIL" 31
fi

# ---------- E2: exact Rust toolchain and frozen upstream ----------
PHASE="E2_RUST_AND_UPSTREAM"
if ! command -v rustup >/dev/null 2>&1; then
  run_cmd rustup_install /bin/bash -lc 'curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain none' || stop "rustup installed" "RUSTUP_INSTALL_FAIL" 40
fi
export PATH="$HOME/.cargo/bin:$PATH"
pass "rustup available"

run_cmd rust_toolchain rustup toolchain install "$RUST_TOOLCHAIN" --profile minimal || stop "Rust $RUST_TOOLCHAIN installed" "RUST_TOOLCHAIN_INSTALL_FAIL" 41
pass "Rust $RUST_TOOLCHAIN installed"
run_cmd rust_default rustup default "$RUST_TOOLCHAIN" || stop "Rust $RUST_TOOLCHAIN selected" "RUST_TOOLCHAIN_SELECT_FAIL" 42
pass "Rust $RUST_TOOLCHAIN selected"
run_cmd rust_targets rustup target add --toolchain "$RUST_TOOLCHAIN" aarch64-apple-ios aarch64-apple-ios-sim || stop "iOS Rust targets installed" "RUST_IOS_TARGET_INSTALL_FAIL" 43
pass "iOS Rust targets installed"
RUSTC_VERSION="$(rustc -V 2>/dev/null || true)"
CARGO_VERSION="$(cargo -V 2>/dev/null || true)"

if run_cmd bootstrap_beankeeper python3 "$REPO_ROOT/scripts/bootstrap_beankeeper.py"; then
  pass "Exact frozen Beankeeper source materialised"
else
  stop "Exact frozen Beankeeper source materialised" "BEANKEEPER_BOOTSTRAP_FAIL" 44
fi
UPSTREAM_HEAD="$(git -C "$REPO_ROOT/upstream/beankeeper" rev-parse HEAD 2>/dev/null || true)"
[ "$UPSTREAM_HEAD" = "$BEANKEEPER_PIN" ] || stop "Beankeeper checkout matches frozen commit" "BEANKEEPER_PIN_MISMATCH" 45
pass "Beankeeper checkout matches frozen commit"

# ---------- E3: locked graph and platform-neutral regression ----------
PHASE="E3_LOCKED_GRAPH"
cd "$WORKSPACE" || exit 46
LOCK_SHA="$(shasum -a 256 Cargo.lock | awk '{print $1}')"
[ "$LOCK_SHA" = "$LOCK_SHA_EXPECTED" ] || stop "Cargo.lock matches reviewed graph" "LOCK_HASH_MISMATCH" 46
pass "Cargo.lock matches reviewed graph"

export CARGO_BUILD_JOBS=1
export CARGO_INCREMENTAL=0
run_cmd cargo_fetch cargo fetch --locked || stop "Reviewed dependency graph fetches with --locked" "CARGO_FETCH_LOCKED_FAIL" 47
pass "Reviewed dependency graph fetches with --locked"
run_cmd foundation_tests cargo test -p shark-foundation --locked --jobs 1 || stop "Shark foundation regression suite passes on Codemagic Mac" "FOUNDATION_TEST_FAIL" 48
pass "Shark foundation regression suite passes on Codemagic Mac"

# ---------- E4: physical iPhone/iPad target compile ----------
PHASE="E4_PHYSICAL_IOS_COMPILE"
run_cmd foundation_device cargo build -p shark-foundation --target aarch64-apple-ios --locked --jobs 1 || stop "Shark foundation compiles for physical aarch64-apple-ios" "FOUNDATION_IOS_DEVICE_COMPILE_FAIL" 50
pass "Shark foundation compiles for physical aarch64-apple-ios"
run_cmd shell_device cargo build -p shark-tauri-spike --target aarch64-apple-ios --locked --jobs 1 || stop "Shark Tauri shell compiles for physical aarch64-apple-ios" "SHELL_IOS_DEVICE_COMPILE_FAIL" 51
pass "Shark Tauri shell compiles for physical aarch64-apple-ios"

LOCK_SHA_AFTER_DEVICE="$(shasum -a 256 Cargo.lock | awk '{print $1}')"
[ "$LOCK_SHA_AFTER_DEVICE" = "$LOCK_SHA_EXPECTED" ] || stop "Cargo.lock unchanged by physical iOS compile" "LOCKFILE_DRIFT" 52
pass "Cargo.lock unchanged by physical iOS compile"

# ---------- E5: pinned Tauri CLI ----------
PHASE="E5_TAURI_CLI"
mkdir -p "$TOOLS"
run_cmd install_tauri_cli cargo install tauri-cli --version "$TAURI_CLI_VERSION" --locked --root "$TOOLS" --force || stop "Pinned Tauri CLI installs" "TAURI_CLI_INSTALL_FAIL" 60
pass "Pinned Tauri CLI installs"
export PATH="$TOOLS/bin:$PATH"
TAURI_VERSION="$(cargo tauri --version 2>/dev/null || true)"
printf '%s' "$TAURI_VERSION" | grep -q "$TAURI_CLI_VERSION" || stop "Pinned Tauri CLI is active" "TAURI_CLI_VERSION_MISMATCH" 61
pass "Pinned Tauri CLI $TAURI_CLI_VERSION is active"

# ---------- E6: unsigned iOS Simulator Tauri shell ----------
PHASE="E6_IOS_SIMULATOR_BUILD"
cd "$TAURI_APP" || exit 62
rm -rf gen/apple permissions/autogenerated
run_cmd tauri_ios_init cargo tauri ios init --ci || stop "Tauri iOS project initialises with platform-specific config" "TAURI_IOS_INIT_FAIL" 62
pass "Tauri iOS project initialises with platform-specific config"

# Reuse the already-reviewed source icon; generated icon variants are build output only.
run_cmd tauri_icons cargo tauri icon "$TAURI_APP/icons/icon.png" || stop "Tauri iOS icon set generates from reviewed source icon" "TAURI_IOS_ICON_FAIL" 63
pass "Tauri iOS icon set generates from reviewed source icon"

export CI=true
export CODE_SIGNING_ALLOWED=NO
export CODE_SIGNING_REQUIRED=NO
export CODE_SIGN_IDENTITY=""
run_cmd tauri_ios_build cargo tauri ios build --target aarch64-sim --debug --ci || stop "Unsigned Tauri iOS Simulator app builds" "TAURI_IOS_SIM_BUILD_FAIL" 64
pass "Unsigned Tauri iOS Simulator app builds"

APP_PATH="$(find "$TAURI_APP/gen/apple" "$WORKSPACE/target" -type d -name '*.app' 2>/dev/null | head -1 || true)"
[ -n "$APP_PATH" ] || stop "Generated iOS Simulator .app is located" "IOS_APP_ARTIFACT_MISSING" 65
pass "Generated iOS Simulator .app is located"

AUTOGEN_COUNT="$(find "$TAURI_APP/permissions/autogenerated" -maxdepth 1 -type f -name '*.toml' 2>/dev/null | wc -l | tr -d ' ')"
[ "$AUTOGEN_COUNT" = "6" ] || stop "Exactly six generated AppManifest permission TOMLs exist after build" "AUTOGENERATED_PERMISSION_COUNT_DRIFT" 66
pass "Exactly six generated AppManifest permission TOMLs exist after build"

if git -C "$REPO_ROOT" ls-files 'workspace/shark-tauri-spike/permissions/autogenerated/*.toml' | grep -q .; then
  stop "Generated AppManifest permissions remain uncommitted" "AUTOGENERATED_PERMISSION_COMMITTED" 67
fi
pass "Generated AppManifest permissions remain uncommitted"

LOCK_SHA_FINAL="$(shasum -a 256 "$WORKSPACE/Cargo.lock" | awk '{print $1}')"
[ "$LOCK_SHA_FINAL" = "$LOCK_SHA_EXPECTED" ] || stop "Reviewed Cargo.lock unchanged through complete SBC-1E gate" "LOCKFILE_DRIFT" 68
LOCK_SHA="$LOCK_SHA_FINAL"
pass "Reviewed Cargo.lock unchanged through complete SBC-1E gate"

PHASE="COMPLETE"
OVERALL="PASS"
CLASSIFICATION="PASS_SBC1E_PHYSICAL_IOS_AND_UNSIGNED_SIMULATOR_SHELL"
exit 0
