// Generated by SharkBooks bounded Action System tooling.
// JSON-schema generator: schemars 1.2.2
// TypeScript generator: ts-rs 12.0.1
// Do not edit manually.

type ActionRegistryCounts = { canonical_actions: number, voice_eligible_canonical_actions: number, aliases: number, utterance_fixtures: number, };

type ActionRegistryPolicy = { voice_adds_no_new_authority: boolean, locked_actions_fail_closed: boolean, confirmation_cannot_be_lowered_by_invocation_surface: boolean, manual_text_voice_platform_intent_share_one_action_identity: boolean, };

type ActionAlias = { alias_action_id: string, target_action_id: string, preset: { [key in string]: string }, label: string, };

type ConfirmationClass = "NONE" | "EXPLICIT" | "STRONG_EXPLICIT";

type SlotSource = "OWNER" | "CONTEXT";

type SlotSpec = { slot_id: string, label: string, required: boolean, source: SlotSource, choices: Array<string>, };

type ActionSpec = { action_id: string, version: number, family: string, manual_label: string, owner_intent: string, implementation_state: string, availability_state: string, evidence_state: string | null, authority_class: string, confirmation_policy: string, confirmation_class: ConfirmationClass, voice_parity: string, voice_eligible: boolean, backend_basis: string, authority_source: string, hard_boundary: string | null, required_slots: Array<SlotSpec>, choice_hints: Array<string>, utterances: Array<string>, backend_state: string, };

type ActionRegistryDocument = { schema: string, date: string, source_authorities: Array<string>, counts: ActionRegistryCounts, policy: ActionRegistryPolicy, aliases: Array<ActionAlias>, actions: Array<ActionSpec>, };
